### ISSUE TITLE
Docs Integration Page - Rockchip/RKNN

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#13566]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

- [ ] new integrations page for Rockchip/RKNN
- [ ] update exports page when integrated
- [ ] include benchmark results

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by Burhan-Q** [comment]
Related to #13564

**Comment by harshdhamecha** [comment]
I just wanted to check if the docs are available now or not. I feel it's not yet available.

**Comment by lakshanthad** [comment]
Hello @harshdhamecha,
Thank you for your interest in RKNN integration.

We are currently in the development phase of this integration and have made significant progress. At this stage, we have successfully exported models to the `RKNN` format and performed inference on Rockchip hardware. Once we've finalized and refined the development work, we will update the documentation and share it here.

Development branch: https://github.com/ultralytics/ultralytics/tree/rknn2

### Working features:

- Using the Ultralytics package on x86 hardware to export a YOLOv8 model to RKNN format.
- Running inference on Rockchip hardware (e.g., RK3588, such as Radxa Rock 5B) with the exported model. The inference is expected to work on other Rockchip devices with an NPU, such as RK3562, RK3566, and RK3568.
- Currently, only detection models are supported.

### TODO:

- [ ] Add support for INT8 quantization.
- [ ] Extend support for classification, segmentation, and pose estimation tasks.

### Steps to follow:

Please follow the below steps to reproduce our workflow at the current stage. This is divided into 2 sections as X86 and rockchip hardware since model needs to be exported on X86 hardware and inference on Rockchip hardware. Also, it is recommended that you work on a `Python Virtual Environment` for both devices. You can activate a virtual environment as follows:

```sh
python3 -m venv env
source env/bin/activate
```

#### On X86 hardware

1. Install [rknn-toolkit2](https://github.com/airockchip/rknn-toolkit2/tree/master/rknn-toolkit2/packages) based on the installed Python version

```sh
# example: for Python3.11
pip install rknn_toolkit2-2.1.0+708089d1-cp311-cp311-linux_x86_64.whl
```

2. Clone `ultralytics` repo and switch to `rknn2` branch

```sh
git clone https://github.com/ultralytics/ultralytics
cd ultralytics
git checkout rknn2
```

3. Install Ultralytics package in editable mode

```sh
pip install -U pip
pip install -e .
```

4. Export a YOLOv8 detection model to `rknn` format. 

```sh
yolo export model=yolov8n.pt format=rknn name=rk3588
```

The exported model will have the name `yolov8n-rk3588.rknn`

> **_NOTE:_**  Here the default option is to export to `rk3588`. Change the `name` argument according to your hardware (rk3562, rk3566, rk3568).

5. Move the exported `.rknn` file and `metadata.yaml` to the Rochchip hardware

#### On Rockchip hardware

1. Install [rknn-toolkit-lite2](https://github.com/airockchip/rknn-toolkit2/tree/master/rknn-toolkit-lite2/packages) based on the installed Python version

```sh
# example: for Python3.11
pip install rknn_toolkit_lite2-2.1.0-cp311-cp311-linux_aarch64.whl
```

> **_NOTE:_**  Some Rockchip based hardware such as Radxa Rock5B includes `rknn_toolkit_lite2` as a `system-wide apt package` out-of-box with their pre-packaged OS. You can check this using `sudo dpkg -l | grep rknn`. However, if the installed version is older than `v2.1.0`, it is recommended to use the above `pip` installation method. 

2. Clone `ultralytics` repo and switch to `rknn2` branch

```sh
git clone https://github.com/ultralytics/ultralytics
cd ultralytics
git checkout rknn2
```

3. Install Ultralytics package in editable mode

```sh
pip install -U pip
pip install -e .
```

4. Move the exported `.rknn` file and `metadata.yaml` to `ultralytics` directory 

5. Start inference

```sh
yolo detect predict model=yolov8n-rk3588.rknn
```

### FAQ

1. Why there is an error about RKNN runtime version not matching with the RKNN Toolkit version?
You might see the below output when running inference on Rochchip hardware 

![image](https://github.com/user-attachments/assets/8dd3f645-1839-4617-929d-6b747ef9a46a)

If this happens, please replace `/usr/lib/librknnrt.so` with [this file](https://github.com/airockchip/rknn-toolkit2/blob/master/rknpu2/runtime/Linux/librknn_api/aarch64/librknnrt.so)

**Comment by yg-dickson** [comment]
Is it not integrated into the official version yet?

**Comment by glenn-jocher** [comment]
The integration is still in development and not yet available in the official version. Please stay tuned for updates.

**Comment by yg-dickson** [comment]
Is it applicable to yolo11?

**Comment by yg-dickson** [comment]
I followed the tutorial above, yolo11 cannot convert rknn, yolov8 can convert rknn normally.

**Comment by yg-dickson** [comment]
When will the official version be released?

**Comment by glenn-jocher** [comment]
The official release date hasn't been announced yet. Please keep an eye on our GitHub repo for updates.

**Comment by acuteyaya** [comment]
I changed the network layers of yolo11 and what should I do if I want to convert to rknn

**Comment by glenn-jocher** [comment]
Custom modifications to the YOLO11 network layers might not be supported by the current RKNN export implementation. RKNN export expects specific layer configurations for compatibility. You can attempt exporting with your changes, but if issues arise, you'll need to align your changes with RKNN's supported operations or modify the export code accordingly. Further, stay updated on RKNN export support for YOLO11 by following development in the [Ultralytics repo](https://github.com/ultralytics/ultralytics).

**Comment by acuteyaya** [comment]
I use rknn-toolkit2（2.3.0-cp38-docker from https://github.com/airockchip/rknn-toolkit2） to convert the YOLO11 model and generate rknn fp model. It can work normally on my board. when I generate rknn int8 model, and the model doesn't recognize anything. The framework I use for inference is  RKNNLite from rknnlite.api. What other methods should I use to quantify the model.

**Comment by acuteyaya** [comment]
I found that the quantized model score is 0.0，because the output box and the score are concatenated together. The output is normal when taken apart
![image](https://github.com/user-attachments/assets/104f0ff0-4cbd-4711-ae9a-b90065d93f88)

**Comment by glenn-jocher** [comment]
It looks like the issue is related to how the quantized model's output tensor is structured. You may need to adjust the post-processing logic to properly separate the bounding boxes and confidence scores. Review RKNN precision issues in the inference framework and ensure the post-processing aligns with the expected tensor format. Adjusting your output parsing should resolve the scoring issue.

**Comment by Digital2Slave** [comment]
> I found that the quantized model score is 0.0，because the output box and the score are concatenated together. The output is normal when taken apart ![image](https://private-user-images.githubusercontent.com/103696125/390200468-104f0ff0-4cbd-4711-ae9a-b90065d93f88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NTg2NTMsIm5iZiI6MTczMjc1ODM1MywicGF0aCI6Ii8xMDM2OTYxMjUvMzkwMjAwNDY4LTEwNGYwZmYwLTRjYmQtNDcxMS1hZTlhLWI5MDA2NWQ5M2Y4OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwMTQ1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmU4MGFmOWYzZThkZTE3NTQ3NjkwZmZkZDUwZTkzZTIzYjU4M2FhOTE4YzgzNmRmZDNmMzc1YmYyNTAyMTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oGi4K4M0AnNbuUvebdMlfUcC5MCduarlUgyaxV3f-w8)

https://github.com/airockchip/ultralytics_yolo11/blob/main/RKOPT_README.md 

Base on https://github.com/ultralytics/ultralytics with commit id as 50497218c25682458ea35b02dcc5d8a364f34591  
`pip install ultralytics==8.3.9`

**Comment by glenn-jocher** [comment]
Thank you for pointing this out. It seems the concatenation issue is specific to the quantized output structure. To address this, you may need to customize the post-processing step in your inference code to properly parse the output tensor, separating the bounding boxes and scores into distinct sections. For further insights, you might want to refer to the RKNN API documentation or inspect the model's exported output structure. Let us know if you encounter any additional challenges.

**Comment by CH-Echo** [comment]
@glenn-jocher I would like to ask a question. When exporting RKNN for v8pose, I divided the model into 9 outputs: detect header and pose header. However, there is a significant difference between the results obtained by running fp16 on RKNN and those obtained by converting pt to engine-fp16. I would like to know if it is because I modified the model structure myself

**Comment by CH-Echo** [comment]
> @glenn-jocher I would like to ask a question. When exporting RKNN for v8pose, I divided the model into 9 outputs: detect header and pose header. However, there is a significant difference between the results obtained by running fp16 on RKNN and those obtained by converting pt to engine-fp16. I would like to know if it is because I modified the model structure myself

By the way, I also replaced the activation function with SiLU ->ReLU

**Comment by glenn-jocher** [comment]
When modifying the model structure (e.g., changing outputs or activation functions), discrepancies in results are expected due to differences in numerical precision and hardware-specific optimizations. These changes may also affect compatibility during exports and inference. I recommend verifying that your modifications align with RKNN's supported operations and ensuring proper post-processing for consistent output interpretation.

**Comment by UltralyticsAssistant** [comment]
The potential fix for this issue has been merged into the main branch via [PR #16308](https://github.com/ultralytics/ultralytics/pull/16308). 🎉 Huge thanks to the author, @IvorZhu331, and contributors @ambitious-octopus, @Laughing-q, @Burhan-Q, @lakshanthad, @MathijsNL, @yg-dickson, and @glenn-jocher for their efforts on this!

### Key Changes:
This PR introduces support for exporting YOLO models to Rockchip's RKNN format, enhancing model deployment capabilities on Rockchip NPUs. Here’s a quick summary of the critical updates that could address this issue:
- **RKNN Export Support**: Added `RKNN` as a new export format for YOLO models to enable seamless deployment on Rockchip devices like the RK3588 and RK3566.
- **Documentation Improvements**: Comprehensive guides are now available to help users with RKNN export and deployment.
- **Code Enhancements**: Updated export workflows, integrated Rockchip compatibility checks, and optimized for Rockchip hardware's performance capabilities.

These changes aim to improve the experience for developers working with Rockchip hardware, allowing for faster and more efficient deployment of YOLO models with hardware-accelerated inference.

### Testing the Fix:
You can test this fix by:
1. Installing the latest changes directly from the repo:
   ```bash
   pip install git+https://github.com/ultralytics/ultralytics.git@main
   ```
2. Alternatively, you can wait for the next official release on PyPI.

### Next Steps:
Your feedback is invaluable! Please try the latest changes and let us know if they resolve the issue. If you experience any further problems, feel free to let us know, and we’ll be happy to assist further.

Thank you for reporting this issue! Your input helps improve the project for everyone. 🙏 Looking forward to hearing your thoughts!

**Comment by alshami1** [comment]
easy way to train and convert yolov8 to rknn full steps:
[https://www.kaggle.com/code/lavirz/yolov8-to-rknn](url)

and for yolov11 this in this [https://www.kaggle.com/code/vrishabmakam/frog-force-503-yolo11-training-rknn-conversion](url)

**Comment by glenn-jocher** [comment]
Thanks for sharing these community resources! For official YOLO11 RKNN conversion steps, we recommend following the [Rockchip RKNN Export Guide](https://docs.ultralytics.com/integrations/rockchip-rknn/) in our documentation. This covers full export workflows and best practices directly supported by our team.

**Comment by glenn-jocher** [comment]
Closing the loop here: RKNN INT8 export is now supported in Ultralytics starting with `ultralytics>=8.4.59`.

Implementation PR: https://github.com/ultralytics/ultralytics/pull/24656
Platform export UI: https://platform.ultralytics.com/ultralytics/yolo26/yolo26n?tab=export

Python usage now follows the same INT8 calibration-data flow as other export formats, for example:

```python
from ultralytics import YOLO

YOLO("yolo26n.pt").export(format="rknn", name="rk3588", int8=True, data="coco8.yaml")
```

Platform also exposes the RKNN FP16/INT8 export controls directly:

<img width="1306" height="1036" alt="Screenshot 2026-06-01 at 17 31 16" src="https://github.com/user-attachments/assets/553404ae-3048-48f9-9fde-02b200991be2" />
