### ISSUE TITLE
Classification augmentations

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#6917]
## Summary
Execute research and testing on new/additional augmentations to use for Classification task.

## Subtasks
- [x] research new/additional augmentations for image classification
- [x] identified new augmentations to test with
- [x] execute new augmentations
- [x] collect and analyze new augmentation performance impacts
- [x] decide which augmentations to include
- [x] implement new augmentations into deployment code
- [ ] release new iteration of classification task with additional/new augmentations

**Comment by Burhan-Q** [comment]
@fcakyon also please reference this issue in relevant PRs/commits
