### ISSUE TITLE
Include YOLOv8x-P6 variant for all tasks

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#6928]
## Summary
Include P6 variant of models for all Ultralytics Tasks

## Tasks
- [x] [YOLOv8-P6](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/models/v8/yolov8-p6.yaml)
- [ ] YOLOv8-cls-P6
- [x] [YOLOv8-seg-P6](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/models/v8/yolov8-seg-p6.yaml)
- [x] [YOLOv8-pose-P6](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/cfg/models/v8/yolov8-pose-p6.yaml)
- [ ] YOLOv8-obb-P6
- [ ] update Ultralytics Documentation

**Comment by Burhan-Q** [comment]
@glenn-jocher looking at the weights files in `ultralytics/assets/releases/tag/v0.0.0` I noticed that the detection models are listed as `yolov8x6.pt`, `yolov8x6-500.pt` (not sure what the 500 is), and `yolov8x6-oiv7.pt` but I thought that naming was intended to be `yolov8x-p6.pt` which I was talking to someone about on Discord yesterday which caused some confusion. I think when they tried using `yolov8x-p6.pt` the `pose` model was downloaded instead of the `detect` model.

![Image](https://github.com/ultralytics/ultralytics/assets/62214284/0551fa7c-5507-476b-b65d-8eb1c6cddaaa)

Additionally, they pointed out that the [docs site](https://docs.ultralytics.com/models/yolov8/#supported-tasks-and-modes) only lists P6 models for the `pose` task. Thought I'd document this here for reference
