### ISSUE TITLE
Add support for n-channel input images

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#6929]
## Summary
Make model input channel count configurable by user. 

## Tasks
- [ ] build out dataset infrastructure
- [ ] update augmentations
- [ ] ...
- [ ] create/update unit tests
- [ ] update Ultralytics Documentation

**Comment by DnEcing** [comment]
Add the ability to load extra picture folders, such as:
images/train/1.jpg (RGB)
images_ir/train/1.jpg (Infrared)
labels/train/1.txt

In data/base.py
Load additional images and splice them with RGB
input_im = cv2.merge((im_ir, im))

**Comment by glenn-jocher** [comment]
@DnEcing hello! Thank you for the feature suggestion. Currently, YOLOv8 is designed to work primarily with standard 3-channel RGB images. Extending support to n-channel images would indeed be a valuable feature, but as you pointed out, it requires significant updates across the codebase, from dataset handling and augmentations to model architecture.

I recommend incorporating this idea into your workflow by modifying the channels during the pre-processing step before feeding them into the model if multi-channel support is critical for your use case. Adjusting the model to natively support n-channels is a substantial endeavor, so for now, manual pre-processing is the most feasible workaround.

If you have further questions or suggestions, please feel free to reach out. Your contributions help make our tools and models better for everyone! 🚀

**Comment by DnEcing** [comment]
**My dataset is formatted as follows:
images/train/1.jpg
images_ir/train/1.jpg
labels/train/1.txt**

I modified the following parts: I successfully loaded corresponding pictures in two images folders, spliced them between input networks, and modified part of the code in augment.py (there are still some modifications that need to be made, but my ability is limited)

**Modification 1:**
ultralytics/data/base.py, in __init__
        # self.im_files = self.get_img_files(self.img_path)
        # ======================Modification======================
        self.hyp = hyp
        self.im_files, self.im_filesir = self.get_img_files(self.img_path, hyp.input_mode)
        # ======================Modification======================

**Modification 2:**
ultralytics/data/base.py, whole function: get_img_files
        def get_img_files(self, img_path, input_mode='RGB'):
                """Read image files."""
                try:
                    f = []  # image files
                    for p in img_path if isinstance(img_path, list) else [img_path]:
                        p = Path(p)  # os-agnostic
                        if p.is_dir():  # dir
                            f += glob.glob(str(p / '**' / '*.*'), recursive=True)
                            # F = list(p.rglob('*.*'))  # pathlib
                        elif p.is_file():  # file
                            with open(p) as t:
                                t = t.read().strip().splitlines()
                                parent = str(p.parent) + os.sep
                                f += [x.replace('./', parent) if x.startswith('./') else x for x in t]  # local to global path
                                # F += [p.parent / x.lstrip(os.sep) for x in t]  # local to global path (pathlib)
                        else:
                            raise FileNotFoundError(f'{self.prefix}{p} does not exist')
        
                    im_files = sorted(x.replace('/', os.sep) for x in f if x.split('.')[-1].lower() in IMG_FORMATS)
                    # self.img_files = sorted([x for x in f if x.suffix[1:].lower() in IMG_FORMATS])  # pathlib
                    assert im_files, f'{self.prefix}No images found'
                    # ======================Modification======================
                    im_filesir = []
                    if input_mode == 'Multi':
                        im_filesir = [x.replace("/images/", "/images_ir/") for x in im_files]
                    # ======================Modification======================
                except Exception as e:
                    raise FileNotFoundError(f'{self.prefix}Error loading data from {img_path}\n{HELP_URL}') from e
                if self.fraction < 1:
                    im_files = im_files[:round(len(im_files) * self.fraction)]
                return im_files, im_filesir

**Modification 3:**
ultralytics/data/base.py, in load_image
        if im is None:  # not cached in RAM
            if fn.exists():  # load npy
                # print(f"'{colorstr('blue', 'bold', 'npy'+fn)}'")
                im = np.load(fn)
            else:  # read image
                # print(f"'{colorstr('blue', 'bold', 'img'+f)}'")
                im = cv2.imread(f)  # BGR
                # ======================Modification======================
                if self.hyp.input_mode=='Multi':
                    imir = cv2.imread(self.im_filesir[i])
                    im = cv2.merge((imir, im))
                # ======================Modification======================
                if im is None:
                    raise FileNotFoundError(f'Image Not Found {f}')

**Modification 4:**
ultralytics/utils/plotting.py
        # Build Image
            mosaic = np.full((int(ns * h), int(ns * w), 3), 255, dtype=np.uint8)  # init
            for i, im in enumerate(images):
                if i == max_subplots:  # if last batch has fewer images than we expect
                    break
                x, y = int(w * (i // ns)), int(h * (i % ns))  # block origin
                im = im.transpose(1, 2, 0)
                # mosaic[y:y + h, x:x + w, :] = im
                # =============Modification=============
                if im.shape[2] > 3:
                    mosaic[y:y + h, x:x + w, :] = im[..., :3]
                else:
                    mosaic[y:y + h, x:x + w, :] = im
                # =============Modification=============

**Modification 5:**
ultralytics/engine/validator.py
        model.eval()
        # model.warmup(imgsz=(1 if pt else self.args.batch, 3, imgsz, imgsz))  # warmup
        # ======================Modification======================
        if self.args.input_mode == 'Multi':
            model.warmup(imgsz=(1 if pt else self.args.batch, 6, imgsz, imgsz))  # warmup
        else:
            model.warmup(imgsz=(1 if pt else self.args.batch, 3, imgsz, imgsz))  # warmup
        # ======================Modification======================

**Modification 6:**
ultralytics/cfg/models/v8/yolov8.yaml
Add key “ch: 6” (Assume the input channel is 6)

**Modification 7:**
ultralytics/cfg/default.yaml
Add key “input_mode: Multi” ("Multi" for n channels input; "RGB" for 3 channels input)

The above modification can successfully load two images and the format of the data set is shown at the top, and it can be successfully spliced into multi-channel input. However, I found that the mAP was always extremely low during training, and I have not yet figured out the reason (the images or images_ir of the dataset that I independently loaded can be trained normally, and the mAP is normal).

Meanwhile, the part of augment.py has not been modified, I tried to modify: 
**ultralytics/data/augment.py, randomHSV:**
        hue, sat, val = cv2.split(cv2.cvtColor(img[...,:3], cv2.COLOR_BGR2HSV)) # modified: img -> img[...,:3]

It seems that **LetterBox** needs to be modified, and I haven't found a way yet

**Comment by glenn-jocher** [comment]
Hello @DnEcing, it's great to see your initiative in advancing YOLOv8's capabilities. The multi-channel input feature is indeed a complex one and requires careful implementation across various parts of the codebase.

From your message, it appears that you've made substantial changes to facilitate the processing of both RGB and IR images. Your implementation strategy seems appropriate and adheres to the necessary parts of the data pipeline to concatenate these channels before network ingestion.

However, it's concerning that you are observing extremely low mAP scores during training. This could be caused by a number of factors including but not limited to the intrinsic nature of your dataset, changes to data augmentation pipelines that have adversely affected learning, or even overfitting due to imbalances or the unique characteristics of the combined data channels.

Regarding your augmentations, whenever altering image properties for multi-channel data, you should ensure that any color space transformations, scaling or normalization, are compatible with the additional IR channel. For example, modifications to augmentations like HSV adjustments would not be applicable to IR channels and should only be applied to RGB channels before merging.

I suggest reviewing each modification step by step and verifying the integration of infrared data preserves the quality of both the visual and infrared features. Also, considering the complexity of these operations, issues could be present in the resizing or interpolation steps.

For further assistance beyond your own testing, you might consider sharing your use case with the community for broader insights. Users working with similar datasets or having faced comparable challenges could provide valuable feedback.

Good luck with your project, and remember, persistence is key to innovation. 🚀

**Comment by DnEcing** [comment]
thank you very much for all your answers，I will continue to explore, and if successful, I will share successful cases at the first time

**Comment by glenn-jocher** [comment]
@DnEcing, you're very welcome! Your determination to explore and contribute is invaluable to the community. We're looking forward to hearing about your progress and any successes you achieve. Keep up the great work! 🌟

**Comment by ronit450** [comment]
@DnEcing any update as I am also working on similar problem

**Comment by BBSingleton** [comment]
@glenn-jocher & @Burhan-Q  I'm currently working on a research project to incorporate MS with RGB so I'm looking at 7-8 bands. I was just wondering how things were tracking with N-channel input support. 

Cheers,
B

**Comment by glenn-jocher** [comment]
Hi @BBSingleton,

Thank you for your interest in incorporating multi-spectral (MS) data with RGB for your research project. As of now, the support for N-channel input is still under consideration and development. We understand the importance of this feature and are working towards it.

In the meantime, you might consider preprocessing your multi-channel data to fit the current 3-channel input model by merging or selecting specific bands. This can be a temporary workaround until full support is available.

Feel free to share any insights or progress you make, as it could benefit the community. If you encounter any specific issues or have further questions, please let us know!

**Comment by ronit450** [comment]
> @glenn-jocher & @Burhan-Q I'm currently working on a research project to incorporate MS with RGB so I'm looking at 7-8 bands. I was just wondering how things were tracking with N-channel input support.
> 
> Cheers, B





so basically in the data folder, find wherever they have used the functions of cv2. replace those functions with any other image reader which can read the images with more bands. I used rasterio 
rasterio.open(img) as src


secondly in the engine and nn folder, find the warmup functions and change the n=3 to number of desired bands you are working on

**Comment by glenn-jocher** [comment]
Hi @ronit450,

Thank you for your patience and for sharing your approach. As of now, native support for N-channel input is still under development. However, your method of using `rasterio` for reading multi-band images and modifying the warmup functions to accommodate more channels is a practical workaround.

For others attempting similar modifications, here’s a brief outline:
1. **Image Reading**: Replace `cv2` functions with `rasterio` to handle multi-band images.
   ```python
   import rasterio
   with rasterio.open('path/to/image') as src:
       img = src.read()
   ```
2. **Model Adjustment**: Modify the warmup functions in the `engine` and `nn` folders to change `n=3` to the number of desired bands.

If you encounter any specific issues or need further assistance, feel free to ask. Your contributions are highly valuable to the community! 🚀

**Comment by BBSingleton** [comment]
@glenn-jocher @ronit450 Thank you for such quick responses!

The use of rasterio seems relatively intuitive for opening images. There are also a few cases where cv2 is used to  perform some augmentations and calculations do you know if I'd need to change these as well or  whether cv2 would be able to handles these? For example: 

ultralytics8channel\ultralytics\data\augment.py:
     7  
     8: import cv2
     9  import numpy as np

   458          # s = 2 ** random.uniform(-scale, scale)
   459:         R[:2] = cv2.getRotationMatrix2D(angle=a, center=(0, 0), scale=s)
   460  

   475              if self.perspective:
   476:                 img = cv2.warpPerspective(img, M, dsize=self.size, borderValue=(114, 114, 114))
   477              else:  # affine
   478:                 img = cv2.warpAffine(img, M[:2], dsize=self.size, borderValue=(114, 114, 114))
   479          return img, M, s

   657              r = np.random.uniform(-1, 1, 3) * [self.hgain, self.sgain, self.vgain] + 1  # random gains
   658:             hue, sat, val = cv2.split(cv2.cvtColor(img, cv2.COLOR_BGR2HSV))
   659              dtype = img.dtype  # uint8

   665  
   666:             im_hsv = cv2.merge((cv2.LUT(hue, lut_hue), cv2.LUT(sat, lut_sat), cv2.LUT(val, lut_val)))
   667:             cv2.cvtColor(im_hsv, cv2.COLOR_HSV2BGR, dst=img)  # no return needed
   668          return labels

   770          if shape[::-1] != new_unpad:  # resize
   771:             img = cv2.resize(img, new_unpad, interpolation=cv2.INTER_LINEAR)
   772          top, bottom = int(round(dh - 0.1)) if self.center else 0, int(round(dh + 0.1))
   773          left, right = int(round(dw - 0.1)) if self.center else 0, int(round(dw + 0.1))
   774:         img = cv2.copyMakeBorder(
   775:             img, top, bottom, left, right, cv2.BORDER_CONSTANT, value=(114, 114, 114)
   776          )  # add border

   850                  instances = Instances.concatenate((instances, ins_flip[[j]]), axis=0)
   851:                 cv2.drawContours(im_new, instances.segments[[j]].astype(np.int32), -1, (1, 1, 1), cv2.FILLED)
   852  
   853:             result = cv2.flip(im, 1)  # augment segments (flip left-right)
   854:             i = cv2.flip(im_new, 1).astype(bool)
   855              im[i] = result[i]

  1378          im_out = np.full((hs, ws, 3), 114, dtype=im.dtype)
  1379:         im_out[top : top + h, left : left + w] = cv2.resize(im, (w, h), interpolation=cv2.INTER_LINEAR)
  1380          return im_out

  1408          top, left = (imh - m) // 2, (imw - m) // 2
  1409:         return cv2.resize(im[top : top + m, left : left + m], (self.w, self.h), interpolation=cv2.INTER_LINEAR)
  1410  

Prior to asking about this, I found on another forum someone dealing with RGBD data using similar processes, I'll put the link to their git here if anyone else is looking at tackling a similar project: https://github.com/g-h-anna/ultralytics4channel

Thank you again for your help!

-B

**Comment by ronit450** [comment]
You have two options here, either you can remove this cv2 functionality and make use of PIL or anything else, but the safer option would be to turn off the augmentation. Yes that would reduce the model performance but use of multi-spectral data outweighs this problem

**Comment by BBSingleton** [comment]
Thanks for the reply!

I've updated all the cv2 functionality to rasterio adjusted all the channel values to 8. However, I continue to get the following errors:

More samples per pixel than can be decoded: 8

WARNING ⚠️ No images found in path/to/labels/train.cache, training may not work correctly. See https://docs.ultralytics.com/datasets for dataset formatting guidance.
Traceback (most recent call last):
  File "c:/path/to/4.Test_Combined_TrainModel.py", line 56, in <module>
    model = model.train(data = "Scripts/Test/Combined/Test_Combined_Dataset.yaml",
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/path/to/ultralytics8channel/ultralytics/engine/model.py", line 650, in train
    self.trainer.train()
  File "C:/path/to/ultralytics8channel/ultralytics/engine/trainer.py", line 204, in train
    self._do_train(world_size)
  File "C:/path/to/ultralytics8channel/ultralytics/engine/trainer.py", line 323, in _do_train
    self._setup_train(world_size)
  File "C:/path/to/ultralytics8channel/ultralytics/engine/trainer.py", line 287, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/path/to/ultralytics8channel/ultralytics/models/yolo/detect/train.py", line 49, in get_dataloader       
    dataset = self.build_dataset(dataset_path, mode, batch_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/path/to/ultralytics8channel/ultralytics/models/yolo/detect/train.py", line 43, in build_dataset        
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == "val", stride=gs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/path/to/ultralytics8channel/ultralytics/data/build.py", line 87, in build_yolo_dataset
    return dataset(
           ^^^^^^^^
  File "C:/path/to/ultralytics8channel/ultralytics/data/dataset.py", line 66, in __init__
    super().__init__(*args, **kwargs)
  File "C:/path/to/ultralytics8channel/ultralytics/data/base.py", line 78, in __init__
    self.labels = self.get_labels()
                  ^^^^^^^^^^^^^^^^^
  File "C:/path/to/ultralytics8channel/ultralytics/data/dataset.py", line 163, in get_labels
    len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 0)

I have the code for this here if you have any suggestions: https://github.com/BBSingleton/ultralytics8channel 

Thanks again for all the help.

-B

**Comment by ronit450** [comment]
make sure you are deleting the cache everytime you are running the code. 
in dataset.py there will a function named _get_item
comment out that function and replace it with this
    def __getitem__(self, i):
        """Returns subset of data and targets corresponding to given indices."""
        f, j, fn, im = self.samples[i]  # filename, index, filename with '.npy' suffix, image array

        if self.cache_ram and im is None:
            with rasterio.open(f) as src:
                im = src.read()
                im = np.transpose(im, (1, 2, 0))
            self.samples[i][3] = im  # Update the cache in RAM

        elif self.cache_disk:
            if not fn.exists():  # If cache file does not exist, create it
                with rasterio.open(f) as src:
                    im = src.read()
                    im = np.transpose(im, (1, 2, 0))
                    np.save(fn.with_suffix('.npy').as_posix(), im, allow_pickle=False)
            else:
                im = np.load(fn.with_suffix('.npy').as_posix())

        else:  # If not using any cache, read directly
            with rasterio.open(f) as src:
                im = src.read()
                im = np.transpose(im, (1, 2, 0))

        # Convert the NumPy array to a PIL Image
        im = Image.fromarray(im.astype(np.uint8))  # Ensure data type is uint8 for proper image handling

        # Apply transformations
        sample = self.torch_transforms(im)
        return {"img": sample, "cls": j}

**Comment by BS-ctrl** [comment]
Thanks for the suggestion!

Unfortunately the issue still persists. Feel free to let me know if you have any other suggestions!

Thank you again.
-B

**Comment by pderrenger** [comment]
Hi @BS-ctrl,

Thanks for the update. Please ensure you're using the latest version of the Ultralytics package. Additionally, try clearing the cache files before each run. If the issue persists, please share a minimal reproducible example so we can investigate further.

**Comment by BS-ctrl** [comment]
Hi @pderrenger thanks for the reply! I cloned the most recent version prior to working on this!

Appologies for the long message I've tried to only include the relevant sections. Below, I've attached the scripts I'm using to run the model and some of the changes I've made to ultralytics. 

Thanks again!
-B

# Model script
```
import sys
import os
import glob

cache_files = glob.glob(r"path\to\Combined\splitimages\images\test\labels\*.cache")
for cache_file in cache_files:
    os.remove(cache_file)
    print(f"Deleted cache file: {cache_file}")

# #Ensure the path to the custom ultralytics package is correct
custom_ultralytics_path = r"path\to\custom_yolo\ultralytics8channel"

# Check if the directory exists
if not os.path.isdir(custom_ultralytics_path):
    raise FileNotFoundError(f"The custom ultralytics path does not exist: {custom_ultralytics_path}")

# Add the path to the system path
if custom_ultralytics_path not in sys.path:
    sys.path.insert(0, custom_ultralytics_path)

# Print sys.path for debugging
print("sys.path:", sys.path)

# Import the YOLO class from the custom path
try:
    from ultralytics import YOLO
    print("Imported YOLO successfully from custom path")
except ModuleNotFoundError as e:
    print(f"Error importing YOLO: {e}")
    raise

# Load the model
model = YOLO("yolov8n.yaml")

# Load the dataset and train the model
model = model.train(data = "Scripts/Test/Combined/Test_Combined_Dataset.yaml",
                    task = "train", 
                    epochs = 10, 
                    imgsz = 640, 
                    batch=16, 
                    save_dir = train_runs_dir_path,
                    project = "Test_Combined_TrainModel",
                    name = "Combined_TrainModel")
```


# . yaml file:

```
path: D:/Dissertation/Data/Tiled Images/Test_Prad/Yolov8/Combined/augmented_images_split  # dataset root dir
train: ../images/train  # train images (relative to 'path') 4 images
val: ../images/val  # val images (relative to 'path') 4 images
test: ../images/test # test images (optional)

nc : 1  # number of classes
ch : 8  # number of channels

names:
  0: seedling  # 0 is the class index
```

# Changes made to ultralytics as seen by commented out lines with "FIXME" 

```
ultralytics8channel\ultralytics\data\base.py:
147 : load_image
def load_image(self, i, rect_mode=True):
        """Loads 1 image from dataset index 'i', returns (im, resized hw)."""
        im, f, fn = self.ims[i], self.im_files[i], self.npy_files[i]
        if im is None:  # not cached in RAM
            if fn.exists():  # load npy
                try:
                    im = np.load(fn)
                except Exception as e:
                    LOGGER.warning(f"{self.prefix}WARNING ⚠️ Removing corrupt *.npy image file {fn} due to: {e}")
                    Path(fn).unlink(missing_ok=True)
                    with rasterio.open(f) as src:
                        im = src.read()
            else:  # read image
                with rasterio.open(f) as src:
                        im = src.read()  # BGR
            if im is None:
                raise FileNotFoundError(f"Image Not Found {f}")

            h0, w0 = im.shape[:2]  # orig hw
            if rect_mode:  # resize long side to imgsz while maintaining aspect ratio
                r = self.imgsz / max(h0, w0)  # ratio
                if r != 1:  # if sizes are not equal
                    w, h = (min(math.ceil(w0 * r), self.imgsz), min(math.ceil(h0 * r), self.imgsz))
                    # im = cv2.resize(im, (w, h), interpolation=cv2.INTER_LINEAR) # FIXME Changed: cv2 to use rasterio
                    with rasterio.env():
                        im = rasterio.warp.resize(im, (w, h), method='bilinear')
            elif not (h0 == w0 == self.imgsz):  # resize by stretching image to square imgsz
                # im = cv2.resize(im, (self.imgsz, self.imgsz), interpolation=cv2.INTER_LINEAR) # FIXME: cv2 might need to be replaced with rasterio
                with rasterio.env():
                    im = rasterio.warp.resize(im, (self.w, self.h), method='bilinear')
            # Add to buffer if training with augmentations
            if self.augment:
                self.ims[i], self.im_hw0[i], self.im_hw[i] = im, (h0, w0), im.shape[:2]  # im, hw_original, hw_resized
                self.buffer.append(i)
                if 1 < len(self.buffer) >= self.max_buffer_length:  # prevent empty buffer
                    j = self.buffer.pop(0)
                    if self.cache != "ram":
                        self.ims[j], self.im_hw0[j], self.im_hw[j] = None, None, None

            return im, (h0, w0), im.shape[:2]  

 206
def cache_images_to_disk(self, i):
        """Saves an image as an *.npy file for faster loading."""
        f = self.npy_files[i]
        if not f.exists():
            with rasterio.open(self.im_files[i]) as src:
                im = src.read()
            np.save(f, im, allow_pickle=False) # FIXME: Changed: rasterio was used to read the image rather than cv2
            # np.save(f.as_posix(), cv2.imread(self.im_files[i], cv2.IMREAD_UNCHANGED), allow_pickle=False)

ultralytics8channel\ultralytics\data\converter.py:
  425
for image_path in TQDM(image_paths, desc=f"Processing {phase} images"):
            if image_path.suffix != ".png":
                continue
            image_name_without_ext = image_path.stem
            with rasterio.open(image_path) as src: # FIXME: Changed to rasterio.open
                img = src.read()
            # img = cv2.imread(str(image_path), cv2.IMREAD_UNCHANGED)
            h, w = img.shape[:2]
            convert_label(image_name_without_ext, w, h, orig_label_dir, save_dir)

 539
for label in tqdm(dataset.labels, total=len(dataset.labels), desc="Generating segment labels"):
        h, w = label["shape"]
        boxes = label["bboxes"]
        if len(boxes) == 0:  # skip empty labels
            continue
        boxes[:, [0, 2]] *= w
        boxes[:, [1, 3]] *= h
        # im = cv2.imread(label["im_file"], cv2.IMREAD_UNCHANGED)
        with rasterio.open(label["im_file"]) as src: # FIXME: Changed to rasterio.open
            im = src.read() 
        sam_results = sam_model(im, bboxes=xywh2xyxy(boxes), verbose=False, save=False)
        label["segments"] = sam_results[0].masks.xyn

ultralytics8channel\ultralytics\data\dataset.py:
The same changes as discussed in above forum.
def getitem(self, i):
        """Returns subset of data and targets corresponding to given indices."""
        f, j, fn, im = self.samples[i] # filename, index, filename with '.npy' suffix, image array

        if self.cache_ram and im is None:
            with rasterio.open(f) as src:
                im = src.read()
                im = np.transpose(im, (1, 2, 0))
            self.samples[i][3] = im  # Update the cache in RAM

        elif self.cache_disk:
            if not fn.exists():  # If cache file does not exist, create it
                with rasterio.open(f) as src:
                    im = src.read()
                    im = np.transpose(im, (1, 2, 0))
                    np.save(fn.with_suffix('.npy').as_posix(), im, allow_pickle=False)
            else:
                im = np.load(fn.with_suffix('.npy').as_posix())

        else:  # If not using any cache, read directly
            with rasterio.open(f) as src:
                im = src.read()
                im = np.transpose(im, (1, 2, 0))

        # Convert the NumPy array to a PIL Image
        im = Image.fromarray(im.astype(np.uint8))  # Ensure data type is uint8 for proper image handling

        # Apply transformations
        sample = self.torch_transforms(im)
        return {"img": sample, "cls": j}

ultralytics8channel\ultralytics\data\split_dota.py:
  178  
 # cv2.imwrite(str(Path(im_dir) / f"{new_name}.jpg"), patch_im) # FIXME: Changed rasterio used to save images
        with rasterio.open(Path(im_dir) / f"{new_name}.tif", "w", **src.profile) as dst:
            dst.write(patch_im)
        label = window_objs[i]
        if len(label) == 0:
            continue

  282
for im_file in tqdm(im_files, total=len(im_files), desc="test"):
        w, h = exif_size(Image.open(im_file))
        windows = get_windows((h, w), crop_sizes=crop_sizes, gaps=gaps)
        # im = cv2.imread(im_file, cv2.IMREAD_UNCHANGED) # FIXME: Changed: rasterio used to read images
        with rasterio.open(im_file) as src:
            im = src.read()
        name = Path(im_file).stem
        for window in windows:
            x_start, y_start, x_stop, y_stop = window.tolist()
            new_name = f"{name}__{x_stop - x_start}__{x_start}___{y_start}"
            patch_im = im[y_start:y_stop, x_start:x_stop]
            # cv2.imwrite(str(save_dir / f"{new_name}.jpg"), patch_im) # FIXME: Changed: rasterio used to save images
            with rasterio.open(str(save_dir / f"{new_name}.tif"), "w", **src.profile) as dst:
                dst.write(patch_im)

ultralytics8channel\ultralytics\data\utils.py:
  186     
# cv2.fillPoly(mask, polygons, color=color) # FIXME: Changed to use rasterio.features.geometry_mask
    with rasterio.Env():
        mask = rasterio.features.geometry_mask(polygons, out_shape=imgsz, transform=rasterio.Affine(1, 0, 0, 0, -1, 0), invert=True)
    nh, nw = (imgsz[0] // downsample_ratio, imgsz[1] // downsample_ratio)
    # return cv2.resize(mask, (nw, nh)) # FIXME: Changed to use rasterio to support all formats
    with rasterio.Env():
        mask = rasterio.warp.resize(mask, (nh, nw), method='nearest')
    return mask

 618
# im = cv2.imread(f, cv2.IMREAD_UNCHANGED) # FIXME: Changed to rasterio.open to support all formats
        with rasterio.open(f) as src:
            im = src.read()
        im_height, im_width = im.shape[:2]
        r = max_dim / max(im_height, im_width)  # ratio
        if r < 1.0:  # image too large
            # im = cv2.resize(im, (int(im_width * r), int(im_height * r)), interpolation=cv2.INTER_AREA) # FIXME: Changed to rasterio
            with rasterio.Env():
                im = rasterio.warp.resize(im, (int(im_width * r), int(im_height * r), im.shape[2]), method='nearest')
        # cv2.imwrite(str(f_new or f), im) # FIXME: Changed to rasterio to support all formats
        with rasterio.open(f_new or f, 'w', **src.profile) as dst:
            dst.write(im)

ultralytics8channel\ultralytics\data\explorer\explorer.py:
 29
def load_image(self, i: int) -> Union[Tuple[np.ndarray, Tuple[int, int], Tuple[int, int]], Tuple[None, None, None]]:
        """Loads 1 image from dataset index 'i' without any resize ops."""
        im, f, fn = self.ims[i], self.im_files[i], self.npy_files[i]
        if im is None:  # not cached in RAM
            if fn.exists():  # load npy
                im = np.load(fn)
            else:  # read image
                # im = cv2.imread(f, cv2.IMREAD_UNCHANGED)  # BGR # FIXME: Changed to rasterio
                with rasterio.open(f) as src:
                    im = src.read()
                if im is None:
                    raise FileNotFoundError(f"Image Not Found {f}")
            h0, w0 = im.shape[:2]  # orig hw
            return im, (h0, w0), im.shape[:2]

        return self.ims[i], self.im_hw0[i], self.im_hw[i]
                    
ultralytics8channel\ultralytics\data\explorer\utils.py:
  82      
for i, imf in enumerate(images):
        # im = cv2.imread(imf, cv2.IMREAD_UNCHANGED) # FIXME: Changed to rasterio 
        with rasterio.open(imf) as src:
            im = src.read()
        # im = cv2.cvtColor(im, cv2.COLOR_BGR2RGB) # FIXME: Changed to rasterio
        h, w = im.shape[:2]

```

**Comment by pderrenger** [comment]
Hi @BS-ctrl,

Thanks for sharing the detailed information and your efforts in adapting the code for multi-channel input using `rasterio`. It looks like you've made significant progress. 

Regarding the error "More samples per pixel than can be decoded: 8," it seems to be related to the image reading process. `rasterio` should handle multi-band images, but ensure that the image data is correctly processed and that the number of channels is consistent throughout the pipeline.

For the cache issue, make sure to clear any existing cache files before running your script. You can add a step to delete cache files at the beginning of your script, as you've done.

Additionally, verify that your dataset paths and formats are correctly specified in the `.yaml` file. The error "not enough values to unpack (expected 3, got 0)" suggests that the dataset might not be correctly loaded or formatted.

If the issue persists, consider debugging by checking the intermediate outputs of the image loading and processing steps to ensure the data is as expected.

Feel free to reach out if you have more questions or need further assistance. Good luck with your project!

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has been merged in the linked PR #20223, which introduces comprehensive multispectral image support throughout the Ultralytics ecosystem.

Key changes include:
- Full support for multi-channel datasets. You can now specify the number of channels in your dataset config, enabling seamless training, validation, prediction, and export with images that have more than 3 channels (such as 10-channel multispectral data).
- All YOLO model trainers, augmentations, and preprocessing steps now dynamically adjust to the dataset’s channel count.
- Model export and inference pipelines have been updated to handle and record the correct number of input channels, with metadata included for exported models.
- Visualization functions now gracefully display multispectral images by using only the first three channels.
- Additional tests ensure reliable multi-channel handling across different workflows.

Special thanks to @Laughing-q for the main implementation and to the contributors @glenn-jocher and @Y-T-G for their support.

To test if this resolves your issue, you can install the latest update:
```
pip install -U ultralytics>=8.3.12
```
Alternatively, you can install directly from the main branch for the most recent changes:
```
pip install git+https://github.com/ultralytics/ultralytics.git@main
```
Or, if you prefer, you can wait for the next official PyPI release.

Please let us know if the changes in this update resolve your issue. Thank you for reporting this, and feel free to share any further feedback if you encounter any other problems! 🙏

**Comment by bzisl** [comment]
@UltralyticsAssistant , in that case, when we train single channel images, the memory used for training is reduced? I mean, the images stored in the GPU memory are still RGB? Are we able to increase the batch size x3 in case of single gray images?
