### ISSUE TITLE
Add new feature - dataset explorer

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/ultralytics#6932]
## Summary
Dataset explorer and utilities for Ultralytics

### Embedding

- Allows user to calculate embeddings as a top level operation in YOLO models.
- Start with detection/segmentation backbones for now, pose, etc. are not that relevant for embeddings.

<p><details>
<summary>Example</summary>

```py
from ultralytics import yolo

model = yolo()
embeddings = model.embed(inputs)
```
</details>

### Data explorer dashboard
  - Similarity search
    - Single image
    - Multiple images
  - SQL query/filtering

  <p><details>
  <summary>Example</summary>

  ```sh
  # CLI example
  yolo explorer {DATASET_NAME}
  ```
  ```py
  from ultralytics import Explorer
  
  exp = Explorer(“coco128.yaml”)
  exp.dashboard()
  ```
  </details>

### Advanced features

  - Search across multiple (selected) datasets
  - Delete redundant data or enrich primary dataset from secondary data sources
  - Upload to HUB and export new dataset

  <p><details>
  <summary>Example</summary>

  ```sh
  # CLI example
  yolo explorer {PRIMARY_DATASET} {SECONDARY_DATA_1} {SECONDARY_DATA_2} …
  ```
  ```py
  from ultralytics import Explorer

  exp_primary = Explorer(“coco128.yaml”) # Core dataset to clean or add to with images from other sources
  
  exp_1 = Explorer(“VOC.yaml”)
  exp_2 = Explorer(“coco.yaml”) 
  
  exp.dashboard(sources=[exp_1, exp_2])
  ```
  </details>

## Tasks
- [ ] Create dashboard
  - [ ] use Ultralytics branding
- [ ] Create utility functions/classes
- [ ] ...
- [ ] write unit test
- [ ] create Ultralytics Documentation

**Comment by Burhan-Q** [comment]
@AyushExel I added the information you shared to this issue and cleaned it up some. I also tried to include sub-tasks, but wasn't certain on what else would be needed. Please reference this issue with your PR and any important commits.

**Comment by Burhan-Q** [comment]
PR #6971 opened to add this feature

**Comment by AyushExel** [comment]
Cool. Advanced features are out of scope for now. Let's only plan on getting these before the anniversary:
* Embedding as a top level model feature
* Explorer pythonic API
* Explorer Dashboard

**Comment by Burhan-Q** [comment]
Minimal embeddings PR #7098

**Comment by Burhan-Q** [comment]
2nd milestone (per @AyushExel message), see #7136 

> Started the Explorer API (2nd milestone) early so we start the review cycle early and it doesn't come as a surprise later on. the size of this PR will end up becoming large, even though I've broken it down into steps because this is basically the backbone of the GUI we will build later on..

## What does it do:

It will provide a simple API for users to programmatically create embeddings and explore their datasets using semantic search or SQL like filters. (And later on even evolve their dataset by adding/removing data points)

## Example usage

```py
from ultralytics import Explorer

exp = Explorer(data="coco128.yaml", model="yolov8n.pt")
exp.build_embeddings() #optional, this will be automatically called

# Semantic Search
imgs = exp.get_similar("path.jpg", limit=20) # also accepts list of images
exp.plot_similar(...) # plots cv2 image mosiac of similar images

# SQL filters. Example this will provide the data points that have atleast 2 persons and 1 horse
imgs = exp.sql("labels LIKE '%person person% AND labels LIKE '%horse%'", limit=20)
```

## To reiterate our discussion:
- This is quite powerful for users to explore their datasets on their own, so we can offer it as a well documented API
- Based on this we'll build the GUI explorer (`streamlit` app, milestone 3)

> One thing I (Ayush) was thinking of doing is using mixin classes. Because some classes become quite large, maybe its better to break them down into multiple classes. For example here the Explorer class can be broken down into:
- ExplorerVectorSearchOps - for all the vector search related Ops
- ExplorerPlottingOps - For all the plotting related Ops
- ExplorerDash - For the streamlit GUI dashboard

and then we can put everything in the same Explorer class by inheriting:

`class Explorer(ExplorerVectorSearchOps, ExplorerPlottingOps, ExplorerDash):`
